services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: "zookeeper"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "127.0.0.1:2181:2181"
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: "kafka"
    depends_on:
      - zookeeper
    ports:
      - "127.0.0.1:9092:9092"
      - "127.0.0.1:29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  matchmaker:
    depends_on:
      - zookeeper
      - kafka
    image: matchmaker:latest
    ports:
      - "127.0.0.1:7000:7000"
volumes:
  kafka_data:
    driver: local
networks:
  orchestrator:
    external: true